# Use Node LTS 20
FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy app files
COPY . .

# Expose Next.js dev server port
EXPOSE 3000

# Run Next.js in dev mode with polling for Docker
CMD ["npm", "run", "dev"]